In [68]:
import numpy as np
import pandas as pd

In [69]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [ ]:
df = pd.read_csv(r'../003_cleaned_data/03_gurgaon_properties.csv')

In [71]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1693,3 BHK Flat in Sector 81 Gurgaon,flat,bestech park view grand spa,2.40,9022.0,2660.0,Super Built up area 2660(247.12 sq.m.),3.0,4.0,NaN,"study room,servant room","123, Sector 81 Gurgaon, Gurgaon, Haryana",8.0,North,0 to 1 Year Old,"['Sapphire 83 Mall', 'NH-8, IMT Manesar', 'Dwa...",Bestech park view grand spa is one of the most...,"['8 Fan', '1 Exhaust Fan', '4 Geyser', '1 Stov...","['Centrally Air Conditioned', 'Security / Fire...","['Green Area5 out of 5', 'Construction5 out of..."
1790,4 BHK Flat in Sector 92 Gurgaon,flat,sare homes,0.95,4250.0,2235.0,Super Built up area 2000(185.81 sq.m.)Built Up...,4.0,3.0,2.0,not available,"Flat T04-1701 Sare Homes Sector 92 Gurgaon, Se...",16.0,East,0 to 1 Year Old,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",Brand new flat. Registry done. You will be the...,"['5 Fan', '1 Exhaust Fan', '9 Light', '1 Curta...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Safety3 out of 5', 'Lifestyle4 out of 5', 'E..."
353,2 BHK Flat in Sector 104 Gurgaon,flat,godrej summit,0.85,5878.0,1446.0,Super Built up area 1446(134.34 sq.m.)Built Up...,2.0,2.0,NaN,study room,"Godrej Summit, Sector-104 Gurgaon, Sector 104 ...",10.0,East,1 to 5 Year Old,"['MG Road Metro Station', 'The Esplanade Mall'...",A north-East facing 2 bhk resale flat is avail...,"['1 Fan', '1 Exhaust Fan', '1 Light', 'No AC',...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4.5 out of 5', 'Construction4 out ..."
2571,3 BHK Flat in Sector 112 Gurgaon,flat,experion windchants,3.40,12134.0,2802.0,Super Built up area 2802(260.31 sq.m.)Built Up...,3.0,3.0,2.0,not available,"Sector 112 Gurgaon, Gurgaon, Haryana",14.0,North-East,1 to 5 Year Old,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...",Experion windchants is one of gurgaon's most s...,"['7 Fan', '1 Exhaust Fan', '1 Geyser', '7 Ligh...","['Water purifier', 'Security / Fire Alarm', 'P...","['Green Area5 out of 5', 'Construction5 out of..."
680,3 BHK Flat in Sector 53 Gurgaon,flat,tulip monsella,5.60,19363.0,2892.0,Super Built up area 2892(268.68 sq.m.),3.0,3.0,NaN,not available,"Sector 53 Gurgaon, Gurgaon, Haryana",1.0,NaN,Jul 2027,"['Sector 53-54 Metro Station', 'Central Plaza ...",Best location in delhi ncr. Bang on golf cours...,"['4 Geyser', '4 AC', '1 Chimney', '3 Wardrobe'...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Lifestyle5 out of 5..."

In [72]:
df.shape

(3962, 20)

In [73]:
df.duplicated().sum()

0

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3962 entries, 0 to 3961
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3962 non-null   object
 1   property_type    3962 non-null   object
 2   society          3961 non-null   object
 3   price            3941 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3962 non-null   object
 7   bedRoom          3961 non-null   float64
 8   bathroom         3961 non-null   float64
 9   balcony          3002 non-null   object
 10  additionalRoom   3962 non-null   object
 11  address          3951 non-null   object
 12  floorNum         3940 non-null   float64
 13  facing           2785 non-null   object
 14  agePossession    3961 non-null   object
 15  nearbyLocations  3755 non-null   object
 16  description      3962 non-null   object
 17  furnishDetails   2930 non-null   object
 18  features         3253 non-null   object
 19  rating           3512 non-null   object
dtypes: float64(6), object(14)
memory usage: 619.2+ KB

In [75]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price                21
price_per_sqft       21
area                 21
areaWithType          0
bedRoom               1
bathroom              1
balcony             960
additionalRoom        0
address              11
floorNum             22
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1032
features            709
rating              450
dtype: int64

In [76]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Sector 95A Gurgaon,flat,the roselia 2,0.45,6475.0,695.0,Built Up area: 695 (64.57 sq.m.)Carpet area: 5...,2.0,2.0,2.0,not available,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",19.0,North,undefined,NaN,Signature roselia 2 bhk. It is a good location...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4.5 out of..."
1,3 BHK Flat in Sector 92 Gurgaon,flat,bestech park view sanskruti,1.55,9687.0,1600.0,Super Built up area 1995(185.34 sq.m.)Carpet a...,3.0,3.0,3.0,servant room,"Sector 92, Sector 92 Gurgaon, Gurgaon, Haryana",17.0,NaN,1 to 5 Year Old,"['Sapphire 93 Mall', 'Dwarka Expressway', 'NH-...",Bestech sanskruti is well maintained society w...,"['3 Wardrobe', '6 Fan', '1 Exhaust Fan', '3 Ge...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Green Area5 out of 5', 'Construction5 out of..."
2,2 BHK Flat in Sector 102 Gurgaon,flat,shapoorji pallonji joyville,1.10,12022.0,915.0,Built Up area: 915 (85.01 sq.m.)Carpet area: 7...,2.0,2.0,1.0,not available,"Sector 102, Sector 102 Gurgaon, Gurgaon, Haryana",7.0,NaN,undefined,NaN,Best in class property available at sector 102...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4.5 out of..."
3,2 BHK Flat in Sohna,flat,signature global park,0.67,5537.0,1210.0,Super Built up area 1210(112.41 sq.m.),2.0,2.0,3.0,pooja room,"001, Sohna, Gurgaon, Haryana",4.0,North-East,1 to 5 Year Old,"['Sector 55-56 metro', 'Global city centre', '...","Signature global park in sohna, gurgaon is a r...",NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction5 out of..."
4,2 BHK Flat in Sector 85 Gurgaon,flat,godrej air,1.40,10000.0,1400.0,Built Up area: 1400 (130.06 sq.m.)Carpet area:...,2.0,2.0,3.0,not available,"Sector 85, Sector 85 Gurgaon, Gurgaon, Haryana",23.0,NaN,undefined,"['Sapphire 83 Mall', 'Sector 86 Road', 'Dwarka...",Multistorey apartment is available for sale. I...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [77]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [78]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Sector 95A Gurgaon,flat,the roselia 2,Sector 95A,0.45,6475.0,695.0,Built Up area: 695 (64.57 sq.m.)Carpet area: 5...,2.0,2.0,2.0,not available,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",19.0,North,undefined,NaN,Signature roselia 2 bhk. It is a good location...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4.5 out of..."
1,3 BHK Flat in Sector 92 Gurgaon,flat,bestech park view sanskruti,Sector 92,1.55,9687.0,1600.0,Super Built up area 1995(185.34 sq.m.)Carpet a...,3.0,3.0,3.0,servant room,"Sector 92, Sector 92 Gurgaon, Gurgaon, Haryana",17.0,NaN,1 to 5 Year Old,"['Sapphire 93 Mall', 'Dwarka Expressway', 'NH-...",Bestech sanskruti is well maintained society w...,"['3 Wardrobe', '6 Fan', '1 Exhaust Fan', '3 Ge...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Green Area5 out of 5', 'Construction5 out of..."
2,2 BHK Flat in Sector 102 Gurgaon,flat,shapoorji pallonji joyville,Sector 102,1.10,12022.0,915.0,Built Up area: 915 (85.01 sq.m.)Carpet area: 7...,2.0,2.0,1.0,not available,"Sector 102, Sector 102 Gurgaon, Gurgaon, Haryana",7.0,NaN,undefined,NaN,Best in class property available at sector 102...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4.5 out of..."
3,2 BHK Flat in Sohna,flat,signature global park,Sohna,0.67,5537.0,1210.0,Super Built up area 1210(112.41 sq.m.),2.0,2.0,3.0,pooja room,"001, Sohna, Gurgaon, Haryana",4.0,North-East,1 to 5 Year Old,"['Sector 55-56 metro', 'Global city centre', '...","Signature global park in sohna, gurgaon is a r...",NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction5 out of..."
4,2 BHK Flat in Sector 85 Gurgaon,flat,godrej air,Sector 85,1.40,10000.0,1400.0,Built Up area: 1400 (130.06 sq.m.)Carpet area:...,2.0,2.0,3.0,not available,"Sector 85, Sector 85 Gurgaon, Gurgaon, Haryana",23.0,NaN,undefined,"['Sapphire 83 Mall', 'Sector 86 Road', 'Dwarka...",Multistorey apartment is available for sale. I...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [79]:
df['sector'] = df['sector'].str.lower()

In [80]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Sector 95A Gurgaon,flat,the roselia 2,sector 95a,0.45,6475.0,695.0,Built Up area: 695 (64.57 sq.m.)Carpet area: 5...,2.0,2.0,2.0,not available,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",19.0,North,undefined,NaN,Signature roselia 2 bhk. It is a good location...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4.5 out of..."
1,3 BHK Flat in Sector 92 Gurgaon,flat,bestech park view sanskruti,sector 92,1.55,9687.0,1600.0,Super Built up area 1995(185.34 sq.m.)Carpet a...,3.0,3.0,3.0,servant room,"Sector 92, Sector 92 Gurgaon, Gurgaon, Haryana",17.0,NaN,1 to 5 Year Old,"['Sapphire 93 Mall', 'Dwarka Expressway', 'NH-...",Bestech sanskruti is well maintained society w...,"['3 Wardrobe', '6 Fan', '1 Exhaust Fan', '3 Ge...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Green Area5 out of 5', 'Construction5 out of..."
2,2 BHK Flat in Sector 102 Gurgaon,flat,shapoorji pallonji joyville,sector 102,1.10,12022.0,915.0,Built Up area: 915 (85.01 sq.m.)Carpet area: 7...,2.0,2.0,1.0,not available,"Sector 102, Sector 102 Gurgaon, Gurgaon, Haryana",7.0,NaN,undefined,NaN,Best in class property available at sector 102...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4.5 out of..."
3,2 BHK Flat in Sohna,flat,signature global park,sohna,0.67,5537.0,1210.0,Super Built up area 1210(112.41 sq.m.),2.0,2.0,3.0,pooja room,"001, Sohna, Gurgaon, Haryana",4.0,North-East,1 to 5 Year Old,"['Sector 55-56 metro', 'Global city centre', '...","Signature global park in sohna, gurgaon is a r...",NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction5 out of..."
4,2 BHK Flat in Sector 85 Gurgaon,flat,godrej air,sector 85,1.40,10000.0,1400.0,Built Up area: 1400 (130.06 sq.m.)Carpet area:...,2.0,2.0,3.0,not available,"Sector 85, Sector 85 Gurgaon, Gurgaon, Haryana",23.0,NaN,undefined,"['Sapphire 83 Mall', 'Sector 86 Road', 'Dwarka...",Multistorey apartment is available for sale. I...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [81]:
df['sector'].value_counts()

sector
sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 81                                                     90
sector 65                                                     90
sector 90                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    59
sector 95                                                     57
sector 56                                                     57
sector 89                                                     56
sector 48                                                     56
sector 70a                                                    54
nirvana country                                               53
sector 70                                                     53
sector 37c                                                    53
sector 84                                                     51
sector-33 sohna                                               51
palam vihar                                                   50
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
dlf phase 2                                                   43
dlf phase 1                                                   43
sector 113                                                    43
sector 61                                                     42
sector 82                                                     42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 77                                                     29
sector 72                                                     29
sector 71                                                     27
sector 54                                                     27
laxman vihar                                                  27
dlf phase 4                                                   26
sector 112                                                    24
sector 33                                                     23
sector 88a                                                    23
dlf phase 3                                                   22
sector 111                                                    22
sector 67a                                                    22
sector 22                                                     20
sector 82a                                                    20
sector 78                                                     19
sector 74                                                     18
sector 63a                                                    18
sector 62                                                     17
sector 91                                                     17
sushant lok phase 3                                           16
sector 110                                                    16
sector 99                                                     16
sector 63                                                     15
sector 60                                                     15
sector 14                                                     15
sector 76                                                     14
gwal pahari                                                   14
sector 52                                                     14
sector 53                                                     14
dlf phase 5                                                   14
rajendra park                                                 14
sector 1 imt manesar                                          14
sector 3                                                      14
laxman vihar phase 2                                          13
sector 46                                                     13
sector 36a                                                    13
uppals southend                                               12
sector 93                                                     12
sohna road                                                    12
sector 38                                                     12
sector 39                                                     12
sector 50                                                     12
sector 31                                                     12
sector 9a                                                     11
ashok vihar phase 3 extension                                 11
sector 47                                                     11
sector 7                                                      10
sector 1a imt manesar                                         10
ashok vihar phase 2                                            9
sector 95a                                                     9
sector 55                                                      9
south city 1                                                   9
sector 4                                                       9
c block sushant lok phase 1                                    8
sector 10a                                                     8
malibu town                                                    8
sector 43                                                      8
palam vihar extension                                          8
sector 89 a                                                    8
mehrauli  road                                                 8
sector 57                                                      8
sector 40                                                      8
sector 59                                                      8
dwarka expressway                                              8
surat nagar 1                                                  7
sector 58                                                      7
mianwali colony                                                7
sector 26                                                      7
new colony                                                     7
sector 51                                                      7
sector 36 sohna                                                7
sector 11                                                      7
jacobpura                                                      6
rajiv nagar                                                    6
sector 5                                                       6
sector 1                                                       6
jyoti park                                                     6
ashok vihar                                                    6
sector 105                                                     5
arjun nagar                                                    5
dayanand colony                                                5
saraswati vihar                                                5
greenwood city                                                 5
sector 30                                                      5
chakkarpur                                                     5
manesar                                                        5
sector 28                                                      5
ansal plaza                                                    5
sector 9                                                       5
sector 80                                                      5
subhash nagar                                                  5
sector 23a                                                     5
sector 2                                                       5
new palam vihar                                                5
sushant lok phase 2                                            5
bhim nagar                                                     4
vishnu garden                                                  4
sector 6                                                       4
surya vihar                                                    4
shivpuri                                                       4
sector 17                                                      4
sector 12a                                                     4
shivaji nagar                                                  4
sector 12                                                      4
garhi harsaru                                                  4
madanpuri                                                      4
new                                                            4
sector 3a                                                      4
valley view estate                                             4
suncity                                                        4
dharam colony                                                  4
krishna colony                                                 4
sector 45                                                      4
baldev nagar                                                   4
imt manesar                                                    4
adarsh nagar                                                   4
sector 36                                                      4
devilal colony                                                 4
bhondsi                                                        4
ravi nagar                                                     4
sector 88b                                                     3
a block sushant lok phase 1                                    3
sector 27                                                      3
sector 15                                                      3
sector 73                                                      3
patel nagar                                                    3
shakti nagar                                                   3
sector 8                                                       3
sector 23                                                      3
prem nagar                                                     3
laxmi garden                                                   3
sector 17b                                                     3
gandhi nagar                                                   3
sector 17a                                                     3
b block sushant lok phase 1                                    3
maruti kunj                                                    3
sector 110 a                                                   3
mg road                                                        3
surat nagar                                                    2
pratap nagar                                                   2
sector 41                                                      2
hira nagar                                                     2
lajpat nagar                                                   2
shanti nagar                                                   2
farukhnagar                                                    2
block a surya vihar                                            2
acharya puri                                                   2
nars                                                           2
sector-11 sohna                                                2
ambience island                                                2
samaspur                                                       2
faridabad road                                                 2
, delhi ncr                                                    2
sector 15 part 1                                               2
mohan nagar                                                    2
sector 21                                                      2
sohna  road                                                    2
sector 32                                                      2
surat nagar phase 2                                            2
sector-2 sohna                                                 2
new palam vihar phase 2                                        2
sheetla colony                                                 2
rajiv chowk                                                    2
new basti                                                      2
daulatabad                                                     2
shankar vihar                                                  2
sector 15 part 2                                               2
new palam vihar phase 1                                        2
bissar                                                         2
west rajiv nagar                                               2
golf course road                                               2
sushant lok                                                    2
rosewood                                                       2
sector 24                                                      2
manohar nagar                                                  2
iffco chowk                                                    2
mayfield garden                                                2
sispal vihar                                                   2
bhawani enclave                                                2
golf course ext road                                           2
part 3 sector 5                                                1
bhora kalan                                                    1
sector 37b                                                     1
near khandsa road                                              1
sector 5 chowk                                                 1
saroop garden rajendra park                                    1
near sector 1 market                                           1
pataudi road                                                   1
bhimgarh kheri phase 3                                         1
hno 13 sagar enclave sura                                      1
huda saraswati vihar                                           1
ravi nager basai road                                          1
bptp                                                           1
vir nagar                                                      1
saraswati enclave                                              1
jacobpura near sadar bazar                                     1
damdma                                                         1
dhankot                                                        1
b1 block sector 57                                             1
sector-5 sohna                                                 1
nirvana country pocket h                                       1
sector 21a faridabad                                           1
sector-35 sohna                                                1
sector 37a                                                     1
park view                                                      1
khandsa                                                        1
alipur                                                         1
hsiidc plot sector 1 imt manesar                               1
laxmna vihar, phase 2                                          1
heritage city                                                  1
jat colony,fazilpur/taj nagar road                             1
carterpuri village                                             1
sector 9b                                                      1
gopal nagar, garhi ghasita, sonipat                            1
sector-7 hous                                                  1
om nagar                                                       1
lucknow                                                        1
new colony, sector 7                                           1
near nand hospital                                             1
kanahi                                                         1
godrej aria , sector 79 ,                                      1
rattan garden                                                  1
south city                                                     1
cyber city                                                     1
sector 4 urban estate                                          1
laxman vihar, railway road,                                    1
civil l                                                        1
g block dlf city phase 1                                       1
ansal's palam vihar                                            1
ashok vihar phase i                                            1
mahalaxmi garden, rajendra place                               1
sultanpur                                                      1
tekchand nagar                                                 1
sector 13                                                      1
anand garden, sector-105                                       1
sector 42                                                      1
sector 17c                                                     1
ats marigold                                                   1
block g sector-57                                              1
sai kunj                                                       1
v block dlf phase 3                                            1
near euro                                                      1
sec 3 bhim vihar part 1 bhimgher kheri                         1
new jyoti park                                                 1
ram nagar                                                      1
mahavir pura                                                   1
block h ashok vihar phase iii extension                        1
ashok vihar phase 3                                            1
udyog vihar phase 1                                            1
old delhi road, opp sector-14                                  1
garauli kalan                                                  1
urban estate, sector 5                                         1
rajiv colony                                                   1
devi lal colony gali no 12 gurgaon nr omkar public school      1
sector-5 sheetla colony                                        1
sadar bazar                                                    1
kheri                                                          1
near pataudi chowk                                             1
naharpur rupa                                                  1
shivji park colony                                             1
begampur khatola                                               1
Name: count, dtype: int64

In [82]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')

In [83]:
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')

In [84]:
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')

In [85]:
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')

In [86]:
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')

In [87]:
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')

In [88]:
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [89]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [90]:
df['sector'].value_counts()

sector
sohna road                    163
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 81                      90
sector 65                      90
sector 90                      90
sector 109                     88
sector 79                      80
sector 104                     73
sector 83                      69
sector 37d                     68
sector 86                      67
sector 50                      65
sector 107                     60
sector 108                     59
sector 56                      57
sector 95                      57
sector 48                      56
sector 89                      56
sector 2                       55
sector 70a                     54
sector 37c                     53
sector 70                      53
sector 43                      53
sector 84                      51
sector-33 sohna road           51
sector 26                      50
sector 49                      48
sector 67                      48
sector 28                      47
sector 66                      46
sector 103                     45
sector 113                     43
sector 25                      43
sector 82                      42
sector 61                      42
sector 7                       39
sector 106                     38
sector 4                       36
sector 99a                     32
sector 54                      31
sector 68                      30
sector 12                      30
sector 72                      29
sector 77                      29
sector 71                      27
sector 24                      24
sector 57                      24
sector 112                     24
sector 14                      23
sector 33                      23
sector 105                     23
sector 88a                     23
sector 111                     22
sector 67a                     22
sector 11                      21
sector 3                       20
sector 22                      20
sector 82a                     20
sector 78                      19
sector 47                      19
gwal pahari                    18
sector 63a                     18
sector 74                      18
sector 91                      17
sector 62                      17
sector 110                     16
sector 99                      16
sector 63                      15
sector 60                      15
sector 1 manesar               14
sector 52                      14
sector 76                      14
sector 53                      14
sector 55                      14
sector 4 phase 2               13
sector 46                      13
sector 6                       13
sector 36a                     13
sector 9                       13
sector 39                      12
sector 31                      12
sohna road road                12
sector 93                      12
sector 38                      12
sector 3 phase 3 extension     11
sector 9a                      11
sector 41                      11
sector 1a manesar              10
sector 13                      10
sector 3 phase 2                9
sector 45                       9
sector 95a                      9
manesar                         9
sector 2 extension              8
sector 59                       8
sector 23                       8
sector 8                        8
sector 10a                      8
dwarka expressway               8
sector 40                       8
sector 17                       8
sector 89 a                     8
c block sector 43               8
sector 36 sohna road            7
sector 58                       7
sector 51                       7
sector 1                        6
sector 21                       6
sector 5                        6
sector 80                       5
sector 30                       5
new sector 2                    5
sector 23a                      5
sector 36                       4
sector 12a                      4
sector 3a                       4
new                             4
b block sector 43               3
maruti kunj                     3
patel nagar                     3
a block sector 43               3
sector 15                       3
sector 110 a                    3
sector 88b                      3
sector 27                       3
sector 17a                      3
sector 17b                      3
sector 73                       3
Name: count, dtype: int64

In [91]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')

In [92]:
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [93]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
267,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2.0,2.0,2.0,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
2280,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2.0,2.0,1.0,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
3224,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4.0,4.0,3.0,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
3410,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4.0,4.0,2.0,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN

In [94]:
df.loc[955,'sector'] = 'sector 37'
df.loc[2800,'sector'] = 'sector 92'
df.loc[2838,'sector'] = 'sector 90'
df.loc[2857,'sector'] = 'sector 76'

In [95]:
df[df['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
392,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2.0,1.0,1.0,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."
1235,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,270.0,Plot area 270(25.08 sq.m.),2.0,2.0,2,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1556,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2.0,2.0,1.0,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
1676,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2.0,2.0,2.0,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
3569,3 Bedroom House for sale in New Palam Vihar,house,independent,new sector 2,1.00,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3.0,2.0,2,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [96]:
df.loc[[1072,1486,3875],'sector'] = 'sector 110'

In [97]:
df.shape

(3803, 21)

In [98]:
df.duplicated().sum()

0

In [99]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Sector 95A Gurgaon,flat,the roselia 2,sector 95,0.45,6475.0,695.0,Built Up area: 695 (64.57 sq.m.)Carpet area: 5...,2.0,2.0,2.0,not available,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",19.0,North,undefined,NaN,Signature roselia 2 bhk. It is a good location...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4.5 out of..."
1,3 BHK Flat in Sector 92 Gurgaon,flat,bestech park view sanskruti,sector 92,1.55,9687.0,1600.0,Super Built up area 1995(185.34 sq.m.)Carpet a...,3.0,3.0,3.0,servant room,"Sector 92, Sector 92 Gurgaon, Gurgaon, Haryana",17.0,NaN,1 to 5 Year Old,"['Sapphire 93 Mall', 'Dwarka Expressway', 'NH-...",Bestech sanskruti is well maintained society w...,"['3 Wardrobe', '6 Fan', '1 Exhaust Fan', '3 Ge...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Green Area5 out of 5', 'Construction5 out of..."
2,2 BHK Flat in Sector 102 Gurgaon,flat,shapoorji pallonji joyville,sector 102,1.10,12022.0,915.0,Built Up area: 915 (85.01 sq.m.)Carpet area: 7...,2.0,2.0,1.0,not available,"Sector 102, Sector 102 Gurgaon, Gurgaon, Haryana",7.0,NaN,undefined,NaN,Best in class property available at sector 102...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4.5 out of..."
3,2 BHK Flat in Sohna,flat,signature global park,sohna road,0.67,5537.0,1210.0,Super Built up area 1210(112.41 sq.m.),2.0,2.0,3.0,pooja room,"001, Sohna, Gurgaon, Haryana",4.0,North-East,1 to 5 Year Old,"['Sector 55-56 metro', 'Global city centre', '...","Signature global park in sohna, gurgaon is a r...",NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction5 out of..."
4,2 BHK Flat in Sector 85 Gurgaon,flat,godrej air,sector 85,1.40,10000.0,1400.0,Built Up area: 1400 (130.06 sq.m.)Carpet area:...,2.0,2.0,3.0,not available,"Sector 85, Sector 85 Gurgaon, Gurgaon, Haryana",23.0,NaN,undefined,"['Sapphire 83 Mall', 'Sector 86 Road', 'Dwarka...",Multistorey apartment is available for sale. I...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [100]:
# features to drop -> property_name, address, description, rating
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [101]:
df.sample(5)

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
1449,flat,tulip petals,sector 89,1.55,10000.0,1550.0,Super Built up area 1550(144 sq.m.),3.0,2.0,3.0,store room,6.0,East,5 to 10 Year Old,"['IRIS Broadway Mall', 'Pataudi Road', 'Dwarka...","['3 Wardrobe', '6 Fan', '1 Exhaust Fan', '2 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
892,house,international city by sobha phase 1,sector 109,6.00,24691.0,2430.0,Plot area 270(225.75 sq.m.),4.0,4.0,3+,"store room,servant room,study room,pooja room",2.0,North-East,1 to 5 Year Old,"['Dwarka sector 21 metro station', 'Pacific D2...",NaN,"['Centrally Air Conditioned', 'Water purifier'..."
2795,house,independent,sohna road road,5.50,5093.0,10799.0,Plot area 1200(1003.35 sq.m.)Built Up area: 35...,3.0,3.0,3+,"pooja room,study room,servant room,others",2.0,West,5 to 10 Year Old,"['Kamal Hospital and Maternity Centre', 'Gobin...","['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
565,flat,smart world orchard,sector 61,2.60,14723.0,1766.0,Super Built up area 1630(151.43 sq.m.),3.0,3.0,2.0,not available,2.0,NaN,Within 6 months,"['Sector 55-56 Metro station', 'Bestech Centra...",[],"['Lift(s)', 'Swimming Pool', 'Park', 'Visitor ..."
3587,flat,raheja vedaanta,sector 108,0.70,4522.0,1548.0,Built Up area: 1548 (143.81 sq.m.)Carpet area:...,2.0,2.0,3.0,not available,1.0,West,undefined,NaN,"['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN

In [102]:
# feature engineering required -> areaWithType, additionalRoom, facing, agePossession, furnishDetails, features

In [103]:
df.duplicated().sum()

122

In [ ]:
import os

# Create the folder if it doesn't exist
os.makedirs('../003_cleaned_data', exist_ok=True)

# Save the file (noting the .. to go up one level from your current notebook folder)
df.to_csv('../003_cleaned_data/04_gurgaon_properties_cleaned.csv', index=False)